base_url = "https://si335.github.io"

title = "Stefan Ivanov"
description = " "
compile_sass = false
highlight_code = true
generate_rss = true

[extra]
henry_links = [
    {url = "/about", name = "About"},
    {url = "/teaching", name = "Teaching"},
    {url = "/other", name = "Other"}
]
henry_github = "https://github.com/si335"

